### ISSUE TITLE
Add possibility to add custom headers from checks

### ISSUE THREAD

**Issue by timohund** [ukfast/laravel-health-check#23]
### What is the feature?

Currently it is possible to configure custom healthchecks what is pretty nice! In addition it would be nice if a check can
also add custom http header to the response in order to react on them by reading that header from the response

### What benefits will this change bring?

You could easly add more information to the response

**Comment by tylerwoonton** [comment]
Hi @timohund,

Thanks for raising an issue. It's great to hear that you like the health-check package! 😄 

Can I ask what benefit(s) you think the custom header would have over the current method of returning data from the check when marking it as `OK` or `PROBLEM`?

Just in case you aren't aware, you can pass contextual information back when setting the check status. See here: https://github.com/ukfast/laravel-health-check/blob/master/src/HealthCheck.php#L26

**Comment by timohund** [comment]
@tylerwoonton 

Thanks for your quick response. I already saw that it is possible to provide additional context. This could also be used to add information like that, but it requires additional (potentially error prone) json parsing on the client side. So it would be nice for automated monitoring systems to just check the value of an specific HTTP_RESPONSE header.

**Comment by Gman98ish** [comment]
I think this could be handled in a middleware. I think the use-case is somewhat nice so it shouldn't be enabled by default, but would something like this work for you?

```php
<?php

use UKFast\HealthCheck\Facade\HealthCheck;
use Closure;

class SetHealthCheckHeaders
{
    public function handle($request, Closure $next)
    {
        $response = $next($request);

        HealthCheck::all()->forEach(function ($check) use ($response) {
            $header = "X-{$check->name()}-status";
            $status = $check->status()->okay() ? 1 : 0;

            $response->headers->set($header, $status)
        });
        
        return $response;
    }
}
```

So you'll get an `X-{check}-response` header with a 1 for success or 0 for failure for each check, e.g.

```
X-redis-status: 1
X-database-status 0
```

Does that solve your problem @timohund ?

**Comment by timohund** [comment]
@Gman98ish Yes i think is solves my problem thx

**Comment by tylerwoonton** [comment]
@timohund Do you want to contribute that middleware into the package? We credit contributions in our `CHANGELOG.md`.

**Comment by tylerwoonton** [comment]
Tagged at `v1.4.0`

Good suggestion @timohund and thanks for adding @Gman98ish. 👍🏻 

https://github.com/ukfast/laravel-health-check/releases/tag/v1.4.0
