### ISSUE TITLE
Backward compatibility Laravel Cache

### ISSUE THREAD

**Issue by nick322** [ukfast/laravel-health-check#50]
### What is the issue?

I found that CacheSchedulerRunning.php & CacheHealthCheck.php both use "cache::put(...)"
The $ttl parameter is not rigorous enough. Before laravel 5.8, $ttl was in minutes.

see: https://laravel-news.com/cache-ttl-change-coming-to-laravel-5-8

**Comment by Gman98ish** [comment]
Closing this after PR #51
