### ISSUE TITLE
Add Degraded health check status

### ISSUE THREAD

**Issue by awarrenlove** [ukfast/laravel-health-check#54]
### What is the feature?

Add a new status to https://github.com/ukfast/laravel-health-check/blob/master/src/Status.php for `Degraded` health checks, along with associated helper methods to report and check for this new status. This would be used for checks that are necessary for full functionality of the application in question but do not result in complete failure of the application.

### What benefits will this change bring?

This will give services an official way to report health of dependencies that do not fully result in service failure without reporting an unhealthy state.

Say there is a service whose controller simply accepts a request and creates a Job to be run later. If the queue is up, but a third-party service the worker needs to process that job is down, the running application is able to continue as it can continue creating Jobs. It would be beneficial to report the worker process unhealthy status without reporting the application as fully unhealthy.

### Additional context

The name `Degraded` seems to be common among other services.

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/degraded

https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/health-enhanced-status.html

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.diagnostics.healthchecks.healthstatus?view=dotnet-plat-ext-5.0

**Comment by awarrenlove** [comment]
I am happy to submit a PR for this myself. However, I wanted to discuss this idea before implementing given its size.

**Comment by tylerwoonton** [comment]
Hey @awarrenlove,

Thanks for opening an issue! 😄 

We think this feature could be really useful. We'd love for you to submit a PR adding support for a `Degraded` status.

@Gman98ish can answer any questions you might have about implementation details.

**Comment by Gman98ish** [comment]
@awarrenlove thanks for the PR, I've tagged it at v1.11.0 

Close this issue off when you're happy, if there are other bits that need changing let us know

**Comment by awarrenlove** [comment]
I believe the existing PR should be sufficient, so I will close this.
