### ISSUE TITLE
Fix Backwards Incompatible Config Additions

### ISSUE THREAD

**Issue by phily245** [ukfast/laravel-health-check#56]
### What is the issue?

In https://github.com/ukfast/laravel-health-check/pull/53/files, new config values were added without a fallback.
This was a breaking change for those who have a custom config file, as the new config now returns null, so the paths change from /health and /ping to both be /.

### Steps To Reproduce

* Update a laravel/lumen application with an existing custom config file to the latest version
* Hit `/ping` and `/health`
* Both get 404 responses

### Expected behaviour

200 responses to `/ping` and `/health` instead of 404s

### Possible fixes

Add a fallback to the config values

### Additional context

N/a

**Comment by tylerwoonton** [comment]
Thanks for this. Let me know if you need anything else, @phily245!
